language: ruby
rvm:
  - 2.6
cache:
  bundler: true
  yarn: true

services:
  - postgresql

branches:
  only:
    - master

before_script:
  - psql -c 'create database mshauri_test;' -U postgres
  - nvm install 8.16
  - nvm use 8.16
  - yarn install

script:
  - npm run lint
  - npm run test
  - bundle exec rubocop
  - bundle exec rake
