language: ruby
rvm:
  - 2.6

services:
  - postgresql

branches:
  only:
    - master

before_script:
  - psql -c 'create database mshauri_test;' -U postgres

script:
  - bundle exec rubocop
  - bundle exec rake
